"""initial model

Revision ID: 9ed3f30bef97
Revises: 1d2cc821255d
Create Date: 2024-07-08 13:21:54.407902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed3f30bef97'
down_revision = '1d2cc821255d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('campers', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('camper_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('camper_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('campers', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
